version: "3.8"
services:
  springboot:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db

  mysql_db:
    image: "mysql/mysql-server:latest"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: nE5kMc7JCGNqwDQM
      MYSQL_ROOT_PASSWORD: nE5kMc7JCGNqwDQN