version: "3"
services: 
  springboot-app:
   # container_name: spring-app
    image: springboot-mysql-poc_springboot
    restart: always
    build: .
    ports:
      - 8080:8080 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
  mysqldb: 
    container_name: mysqldb
    image: mysql
    volumes:
      -  /Users/gangatamang/workspace/volume-db:/var/lib/mysql
    ports: 
     - 3306:3306   
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: root
        